[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "colss"
version = "0.3.1"
description = "Fast Mathematical exp evaluator for numpy"
authors = [{name = "Siva Prasad A"}]
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
Source = "https://github.com/SivaPA08/colss"
